Repository JupiterOne/graph-github, pull requests merged in 2023-07, with the labels that each got.

#256 Create Packages from Integration
  .github/workflows/package-publish.yml
  Dockerfile
Labels: release, patch

#260 Collector package deployment step update for E2E tests
  .github/workflows/package-publish.yml
  docs/jupiterone.md
Labels: bug, release, minor

#263 removal of config.enabledDependabotAlerts
  .env.example
  CHANGELOG.md
  src/config.ts
  src/getStepStartStates.test.ts
  src/getStepStartStates.ts
  src/steps/vulnerabilityAlertsSteps.test.ts
Labels: release, minor

#264 INT-7885 - separate nested queries in diferrent requests for pull requests
  src/actions/partialIngestActionHandler.ts
  src/client.ts
  src/client/GraphQLClient/__snapshots__/utils.test.ts.snap
  src/client/GraphQLClient/client.ts
  src/client/GraphQLClient/pullRequestQueries/CommitsQuery.test.ts
  src/client/GraphQLClient/pullRequestQueries/CommitsQuery.ts
  src/client/GraphQLClient/pullRequestQueries/LabelsQuery.test.ts
  src/client/GraphQLClient/pullRequestQueries/LabelsQuery.ts
  src/client/GraphQLClient/pullRequestQueries/PullRequestsQuery.test.ts
  src/client/GraphQLClient/pullRequestQueries/PullRequestsQuery.ts
  src/client/GraphQLClient/pullRequestQueries/ReviewsQuery.test.ts
  src/client/GraphQLClient/pullRequestQueries/ReviewsQuery.ts
  src/client/GraphQLClient/pullRequestQueries/SinglePullRequestQuery.ts
  src/client/GraphQLClient/pullRequestQueries/__snapshots__/CommitsQuery.test.ts.snap
  src/client/GraphQLClient/pullRequestQueries/__snapshots__/LabelsQuery.test.ts.snap
  src/client/GraphQLClient/pullRequestQueries/__snapshots__/PullRequestsQuery.test.ts.snap
  src/client/GraphQLClient/pullRequestQueries/__snapshots__/ReviewsQuery.test.ts.snap
  src/client/GraphQLClient/pullRequestQueries/__snapshots__/SinglePullRequestQuery.test.ts.snap
  src/client/GraphQLClient/pullRequestQueries/testResponses.ts
  src/client/GraphQLClient/types/client.ts
  src/client/GraphQLClient/utils.test.ts
  src/client/GraphQLClient/utils.ts
  src/client/OrganizationAccountClient.ts
  src/steps/__recordings__/pullRequests_4029166752/recording.har
  src/steps/__snapshots__/pullRequests.test.ts.snap
  src/steps/pullRequests.test.ts
  src/steps/pullRequests.ts
  src/sync/__snapshots__/converters.test.ts.snap
  src/sync/converters.test.ts
  src/sync/converters.ts
  src/sync/fixtures/pullRequest.ts
Labels: release, patch

#266 INT-7885 - add config for pull requests search limit
  .env.example
  src/client.ts
  src/client/GraphQLClient/client.ts
  src/client/GraphQLClient/pullRequestQueries/PullRequestsQuery.test.ts
  src/client/GraphQLClient/pullRequestQueries/PullRequestsQuery.ts
  src/client/GraphQLClient/pullRequestQueries/ReviewsQuery.test.ts
  src/client/GraphQLClient/pullRequestQueries/ReviewsQuery.ts
  src/client/GraphQLClient/pullRequestQueries/__snapshots__/ReviewsQuery.test.ts.snap
  src/client/OrganizationAccountClient.ts
  src/config.ts
  src/steps/pullRequests.ts
Labels: release, minor

#267 [INT-8773] - Refactor validate invocation
  package.json
  src/config.ts
  src/getStepStartStates.test.ts
  src/getStepStartStates.ts
  yarn.lock
Labels: release, minor

#269 Add validate invocation to invocation config
  src/index.ts
Labels: release, patch

#268 INT-8436 - Use external identifiers for better email resolution
  CHANGELOG.md
  src/client.ts
  src/client/GraphQLClient/client.ts
  src/client/GraphQLClient/memberQueries/ExternalIdentifiersQuery.ts
  src/client/GraphQLClient/types/client.ts
  src/client/OrganizationAccountClient.ts
  src/steps/__recordings__/branchProtectionRules_2658866605/recording.har
  src/steps/__recordings__/collaborators_232585722/recording.har
  src/steps/__recordings__/issues_2054159433/recording.har
  src/steps/__recordings__/members_937576464/recording.har
  src/steps/__recordings__/pullRequests_4029166752/recording.har
  src/steps/__recordings__/teamMembers_1856808695/recording.har
  src/steps/__snapshots__/branchProtectionRules.test.ts.snap
  src/steps/__snapshots__/collaborators.test.ts.snap
  src/steps/__snapshots__/issues.test.ts.snap
  src/steps/__snapshots__/members.test.ts.snap
  src/steps/__snapshots__/teamMembers.test.ts.snap
  src/steps/members.ts
  src/sync/converters.ts
Labels: release, minor

#270 INT-8436 - Add check to handle when external identifiers aren't available.
  src/steps/members.ts
Labels: release, patch
